services:

  app:
    container_name: latihan
    build:
      context: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_HOST_PORT:$NODE_DOCKER_PORT
      - "9229:9229" #debug port
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_HOST_PORT

    volumes:
      - ./src:/src #read only
      - /src/node_modules #avoid write node_modules

    stdin_open: true #keep open the terminal after building container
    tty: true #keep open the terminal after building container
    command: npm run dev

    networks:
      - latihan-network

networks:
  latihan-network:
    driver: bridge
